config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'order_histories/index'
  end

  root 'home#index'
  
  namespace :api do
    resources :roles, :session, :ship_types, :profile, :users, :orders, :device_tokens, :order_histories
    
    get '/profile/getProfileByUserId/:user_id' => 'profile#getProfleByUserId', :as => 'getProfileByUId'
    get '/getUserProfile' => 'profile#getUserProfile', :as => 'getUserProfile'
    post '/orders/updateOrderStatus/:id' => 'orders#updateOrderStatus', :as => 'updateOrderStatus'
    post '/orders/updateShipper/:id' => 'orders#updateShipper', :as => 'updateShipper'
    post '/orders/import' => 'orders#import', :as => 'importOrder'
    post '/users/getUserByCB' => 'users#getByChatbot', :as => 'getByChatbot'
    post '/orders/caculatingOrder' => 'orders#caculatingOrder', :as => 'caculatingOrder'
    post '/users/getShipperByFullName' => 'users#getShipperByFullName', :as => 'getShipperByFullName'
    post '/users/getListShipper' => 'users#getListShipper', :as => 'getListShipper'
  end
  
  namespace :management do
    resources :dashboard, :roles, :users, :profiles, :order_statuses, :ship_types, :promotions, :orders, :customer_types, :order_histories, :order_analyzes
    get '/my-profile' => 'profiles#edit', :as => 'my-profile'
    get '/import_order' => 'orders#importView', :as => 'importView'
    get '/addForCustomerView' => 'orders#addForCustomerView', :as => 'addForCustomerView'
    post '/addForCustomer' => 'orders#addForCustomer', :as => 'addForCustomer'
    post '/import' => 'orders#import', :as => 'import'
    patch 'update-profile' => 'profiles#update', :as => 'update-profile'
    post '/dang-ky' => 'users#create', :as => 'dang-ky'
    post '/orders/caculatingOrder' => 'orders#caculatingOrder', :as => 'caculatingOrder'
    post '/orders/updateOrderStatus' => 'orders#updateOrderStatus', :as => 'updateOrderStatus'
    post '/users/getListShipper' => 'users#getListShipper', :as => 'getListShipper'
    post '/users/refreshToken' => 'users#refreshToken', :as => 'refreshToken'
    
  end
  
  resources :home, :session
  
  get '/dang-xuat' => 'session#destroy', :as => 'dang-xuat'
  get '/dang-nhap' => 'session#new', :as => 'dang-nhap'
  

end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
end

app/controllers/api/roles_controller.rb
class Api::RolesController < Api::ApplicationController
  before_action :set_post, only: [:show, :update, :destroy]
  
  def create
    @role = Role.new(role_params)
    
    if @role.save
        render json: {
         "status": :create,
         "code": "200",
         "messages":"",
         "result": @role
        }
    else
        render json: {
         "status": :unprocessable_entity,
         "code": "500",
         "messages": @role.errors,
         "result": ""
        }
    end
  end

  def index
    @roles = Role.where(delete_flag: 0).all
    render json: {
     "status": "OK",
     "code": "200",
     "messages":"",
     "result": @roles
    }
  end

  def show
    render json: {
     "status": "OK",
     "code": "200",
     "messages":"",
     "result": @role
    }
  end
  
  def update
      if @role.update(role_params)
          render json: {
           "status": "OK",
           "code": "200",
           "messages":"",
           "result": @role
          }
      else
          render json: {
           "status": :unprocessable_entity,
           "code": "500",
           "messages": @role.errors,
           "result": ""
          }
      end
  end
  
  def destroy
  end
  
  private
    
    def set_post
      @role = Role.find(params[:id])    
    end
    
    
    def post_params
        params.require(:post).permit!
    end
end

app/controllers/management/application_controller.rb
class Management::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper
  include Management::OrdersHelper
  
  helper_method :current_user, :is_admin?
  
  layout 'management/admin'
  
  
  # before_action :set_locale
  
  # def change_locale_path
  #     #if current_user
  #     #  current_user.locale = params[:locale]
  #     #  current_user.save
  #     #else
  #       I18n.locale = params[:locale]
  #     #end
      
  #     #redirect_to root_url  
  #     #redirect_to :back
  # end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def is_admin?
    self.current_user.role.name == "Admin"
  end
  
  def is_member?
    self.current_user.role.name == "Thành Viên"
  end
  
  def verify_logged
    if session[:user_id].nil?
      redirect_to new_session_path
    else
      params[:user_id] = session[:user_id]
    end
  end
  
  # private
  #   def set_locale
  #     I18n.locale = params[:locale] if params[:locale].present?
  #     # current_user.locale
  #     # request.subdomain
  #     # request.ENV["HTTP_ACCEPT_LANGUAGE"]
  #     # request.remote_ip
  #     # current_uri = request.env['PATH_INFO']
      
  #     # unless current_uri == "/"+params[:locale]+"/admin/dashboard" 
  #     #   redirect_to admin_dashboard_index_path
  #     # end
  #   end
  
  #   def default_url_options(options = {})
  #     {locale: I18n.locale}.merge options
  #   end
    
    
end

app/controllers/management/customer_types_controller.rb
class Management::CustomerTypesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @customerType = CustomerType.new
  end

  def create
    @customerType = CustomerType.new(customerType_params)
    @customerType.created_by = current_user.name
    @customerType.updated_by = current_user.name
    @customerType.delete_flag = 0
    
    if @customerType.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_customer_types_path
    else
      flash[:success] = 'Tạo mới thất bại, vui lòng kiểm tra lại'
      render 'new'
    end
  end

  def index
    @customerTypes = CustomerType.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def customerType_params
      params.require(:customer_type).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/dashboard_controller.rb
class Management::DashboardController < Management::ApplicationController
  before_filter :verify_logged
  
  def index
    #get tổng số đơn
    @totalOrder = Order.where(created_by: current_user.id.to_s, delete_flag: 0).size.to_s
    
    #get đơn hàng trong tuần
    #curDate = Date.new.week
    #byebug
  end
end

app/controllers/management/order_analyzes_controller.rb
class Management::OrderAnalyzesController < Management::ApplicationController
  def index
    unless params[:shipperId].nil?
      
      unless params[:fromDate].nil?
        @fromDate = params[:fromDate]
      end
      
      unless params[:toDate].nil?
        @toDate = params[:toDate]
      end
      
      fDate = @fromDate.to_date
      fDate = (fDate-1).to_s + " 17:00:00"
      
      tDate = @toDate.to_date
      tDate = tDate.to_s + " 16:59:59"
      
      @orders = Order.where("updated_at": fDate..tDate).order(id: :desc)
      
      if params[:orderStatusId] != "0"
        @orders = @orders.where('order_status_id': params[:orderStatusId].to_i)
      end
      
      if params[:shipperId] != "0"
        @orders = @orders.where('shipper_id': params[:shipperId].to_i)
      end
      
      if params[:senderId] != "0"
        cusName = User.find(params[:senderId]).profile.full_name
        @lsCustomerId = Sender.where(name: cusName, delete_flag: 0).select(:id)
        @orders = @orders.where(sender_id: @lsCustomerId)
      end
      
      @totalCod = @orders.sum("cod")
      @totalFee = @orders.sum("total")
      
    end
    
    #Order.where('updated_at': "2017-07-22 17:00:00".."2017-07-23 16:59:59")
    
    @users = User.includes(:profile).where(delete_flag: 0, role_id: 2)
    @customer = User.includes(:profile).where(delete_flag: 0, role_id: 3)
    @orderStatus = OrderStatus.where(delete_flag: 0)
  end
end

app/controllers/management/order_histories_controller.rb
class Management::OrderHistoriesController < Management::ApplicationController
  def index
    if params[:orderId].nil?
      @orders = nil
    else
      order = Order.find_by(order_code: params[:orderId])
      unless order.nil?
        @orders = OrderHistory.where(order_id: order.id)
      end
    end
    
  end
end

app/controllers/management/order_statuses_controller.rb
class Management::OrderStatusesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @order_status = OrderStatus.new
  end

  def create
    @order_status = OrderStatus.new(order_status_params)
    @order_status.created_by = "Admin"
    @order_status.updated_by = "Admin"
    @order_status.delete_flag = 0
    
    if @order_status.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_order_statuses_path
    else
      render 'new'
    end
  end

  def index
    @order_statuses = OrderStatus.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def order_status_params
      params.require(:order_status).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/profiles_controller.rb
class Management::ProfilesController < Management::ApplicationController
  before_filter :verify_logged 
  
  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    
    @profile = Profile.find_by(user_id: current_user.id)
    @profile.full_name = params[:profile][:full_name]
    @profile.address = params[:profile][:address]
    @profile.district = params[:profile][:district]
    @profile.city = "Đà Nẵng"
    @profile.updated_at = DateTime.now
    @profile.updated_by = current_user.name
    
    @user = User.find_by(id: current_user.id)
    @user.email = params[:user][:email]
    @user.phone = params[:user][:phone]
    
    if @profile.save && @user.save
      flash[:success] = 'Cập nhật thông tin thành công'
      redirect_to management_my_profile_path
    else
      flash[:error] = 'Cập nhật Thất bại, vui lòng kiểm tra lại'
      redirect_to management_my_profile_path
    end
    
  end
  
end

app/controllers/management/promotions_controller.rb
class Management::PromotionsController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotion_params)
    @promotion.created_by = "Admin"
    @promotion.updated_by = "Admin"
    @promotion.delete_flag = 0
    
    if @promotion.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_promotions_path
    else
      render 'new'
    end
  end

  def index
    @promotions = Promotion.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def promotion_params
      params.require(:promotion).permit(:code, :discount, :discount_from, :discount_to, :count, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/roles_controller.rb
class Management::RolesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @role.created_by = "Admin"
    @role.updated_by = "Admin"
    @role.delete_flag = 0
    
    if @role.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_roles_path
    else
      render 'new'
    end
  end

  def index
    @roles = Role.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    
    
  
    def role_params
      params.require(:role).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/ship_types_controller.rb
class Management::ShipTypesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @ship_type = ShipType.new
  end

  def create
    @ship_type = ShipType.new(ship_type_params)
    @ship_type.created_by = "Admin"
    @ship_type.updated_by = "Admin"
    @ship_type.delete_flag = 0
    
    if @ship_type.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_ship_types_path
    else
      render 'new'
    end
  end

  def index
    @ship_types = ShipType.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def ship_type_params
      params.require(:ship_type).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/users_controller.rb
class Management::UsersController < Management::ApplicationController
  before_filter :verify_logged, :except => [:create, :getListShipper]
  
  def new
    @user = User.new
  end

  def create
    
    if params["email"].nil?
      @user = User.new(user_params)
      @user.created_by = current_user.name
      @user.updated_by = current_user.name
    else
      @user = User.new
      @user.email = params["email"]
      @user.phone = params["phone"]
      @user.password = params["password"]
      if @user.role_id.nil?
        @user.role_id = 3
      end
      @user.created_by = "system"
      @user.updated_by = "system"
    end
    
    #generate Token
    
    o = [('a'..'z'), ('A'..'Z'), (0..9)].map(&:to_a).flatten
    @user.token = (0...32).map { o[rand(o.length)] }.join
    
    @user.provider = "Website"
    @user.delete_flag = 0
    
    #TODO: 
    #kiem tra user da ton tai hay chua (name/email/sdt)
    if User.isUserValid?(@user.name, @user.phone)
      if @user.save
        #create profile for user
        @profile = Profile.new
        @profile.user_id = @user.id
        @profile.delete_flag = 0
        @profile.created_by = "system"
        @profile.updated_by = "system"
        
        if @profile.save
          flash[:success] = 'Tạo mới thành công'
          sign_in @user
          if params["email"].nil?
            redirect_to management_users_path
          else
            redirect_to management_my_profile_path
          end
        end
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.email = params["user"]["email"]
    @user.phone = params["user"]["phone"]
    @user.name =  params["user"]["name"]
    @user.role_id = params["user"]["role_id"]
    @user.customer_type_id = params["user"]["customer_type_id"]
    
    if @user.save
      flash[:success] = 'Cập nhật thành công'
      redirect_to management_users_path
    else
      flash[:success] = 'Cập nhật Thất bại'
      render 'edit'
    end
  end

  def index
    @users = User.where(delete_flag: 0).all
  end

  def show
  end

  def destroy
  end
  
  def getListShipper
    @users = User.includes(:profile).where(delete_flag: 0, role_id: 2)
    
    render json: {
      "resultData" => {
        "listShipper" => @users.as_json(except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag],
                include: {
                  profile: {
                    except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag]
                  }
                }
              )
      }
    }
    
  end
  
  def refreshToken
    userId = params["id"]
    user = User.find(userId)
    o = [('a'..'z'), ('A'..'Z'), (0..9)].map(&:to_a).flatten
    user.token = (0...32).map { o[rand(o.length)] }.join
    
    if user.save
      render json: {
        "resultData" => {
          "msg" =>  "ok",
          "token" => user.token
        }
      }
    end
    
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :role_id, :userstatus_id, :customer_type_id, :email, :phone, :password, :token)
    end
end

app/helpers/api/roles_helper.rb
module Api::RolesHelper
end

app/helpers/management/customer_types_helper.rb
module Management::CustomerTypesHelper
end

app/helpers/management/dashboard_helper.rb
module Management::DashboardHelper
end

app/helpers/management/order_analyzes_helper.rb
module Management::OrderAnalyzesHelper
end

app/helpers/management/order_histories_helper.rb
module Management::OrderHistoriesHelper
end

app/helpers/management/order_statuses_helper.rb
module Management::OrderStatusesHelper
end

app/views/management/roles/create.html.erb
<h1>Admin::Roles#create</h1>
<p>Find me in app/views/admin/roles/create.html.erb</p>

app/views/management/roles/destroy.html.erb
<h1>Admin::Roles#destroy</h1>
<p>Find me in app/views/admin/roles/destroy.html.erb</p>

app/views/management/roles/edit.html.erb
<h1>Admin::Roles#edit</h1>
<p>Find me in app/views/admin/roles/edit.html.erb</p>

app/views/management/roles/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Quản lý Quyền <small></small></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Tìm kiếm">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <%= render 'partials/management/notification' %>
          <%= link_to "Thêm mới", new_management_role_path, class: "btn btn-success pull-right" %>
          
          <div class="x_content">
             
            <div class="table-responsive">
              <table class="table table-striped jambo_table bulk_action">
                <thead>
                  <tr class="headings">
                    <th>
                      <input type="checkbox" id="check-all" class="flat">
                    </th>
                    <th class="column-title">ID </th>
                    <th class="column-title">Tên Quyền</th>
                    <th class="column-title">Mô tả</th>
                    <th class="column-title">Ngày Tạo</th>
                    <th class="column-title">Ngày cập nhật</th>
                    <th class="column-title no-link last"><span class="nobr">Actions</span>
                    </th>
                    
                  </tr>
                </thead>

                <tbody>
                  <% @roles.each do |f| %>
                    <tr class="even pointer">
                      <td class="a-center ">
                        <input type="checkbox" class="flat" name="table_records">
                      </td>
                      <td class=" "><%= f.id %></td>
                      <td class=" "><%= f.name %> </td>
                      <td class=" "><%= f.description %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %></td>
                      <td class=" "><%= f.created_at.to_time.strftime('%B %e at %l:%M %p') %> </td>
                      <td class=" "><%= link_to "Cập Nhật", edit_management_role_path(f), class:'btn btn-primary' %> 
                        <%= link_to "Xóa", management_role_path(f), class:'btn btn-danger', method: :delete, data: {confirm: "Bạn có muốn xóa thông tin này ???"} %>
                      </td>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/management/roles/new.html.erb
<div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Quản lý Quyền<small></small></h3>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_content">
                    <%= form_for [:management, @role], :html => {:class => 'form-horizontal form-label-left'} do |f| %>
                      </p>
                      <span class="section">Thêm Quyền</span>

                      <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Tên<span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :name, class:'form-control col-md-7 col-xs-12', 'data-validate-left-range' =>'5', 'data-validate-words' =>'1', placeholder:'', 'required' => 'required' %>
                        </div>
                      </div>
                      <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Mô tả<span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :description, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                        </div>
                      </div>
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                          <%= link_to "Hủy", management_roles_path, class:'btn btn-primary' %>
                          <%= f.submit "OK", class:'btn btn-success' %>
                        </div>
                      </div>
                      <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

app/views/management/roles/show.html.erb
<h1>Admin::Roles#show</h1>
<p>Find me in app/views/admin/roles/show.html.erb</p>

app/views/management/roles/update.html.erb
<h1>Admin::Roles#update</h1>
<p>Find me in app/views/admin/roles/update.html.erb</p>