config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'order_histories/index'
  end

  root 'home#index'
  
  namespace :api do
    resources :roles, :session, :ship_types, :profile, :users, :orders, :device_tokens, :order_histories
    
    get '/profile/getProfileByUserId/:user_id' => 'profile#getProfleByUserId', :as => 'getProfileByUId'
    get '/getUserProfile' => 'profile#getUserProfile', :as => 'getUserProfile'
    post '/orders/updateOrderStatus/:id' => 'orders#updateOrderStatus', :as => 'updateOrderStatus'
    post '/orders/updateShipper/:id' => 'orders#updateShipper', :as => 'updateShipper'
    post '/orders/import' => 'orders#import', :as => 'importOrder'
    post '/users/getUserByCB' => 'users#getByChatbot', :as => 'getByChatbot'
    post '/orders/caculatingOrder' => 'orders#caculatingOrder', :as => 'caculatingOrder'
    post '/users/getShipperByFullName' => 'users#getShipperByFullName', :as => 'getShipperByFullName'
    post '/users/getListShipper' => 'users#getListShipper', :as => 'getListShipper'
  end
  
  namespace :management do
    resources :dashboard, :roles, :users, :profiles, :order_statuses, :ship_types, :promotions, :orders, :customer_types, :order_histories, :order_analyzes
    get '/my-profile' => 'profiles#edit', :as => 'my-profile'
    get '/import_order' => 'orders#importView', :as => 'importView'
    get '/addForCustomerView' => 'orders#addForCustomerView', :as => 'addForCustomerView'
    post '/addForCustomer' => 'orders#addForCustomer', :as => 'addForCustomer'
    post '/import' => 'orders#import', :as => 'import'
    patch 'update-profile' => 'profiles#update', :as => 'update-profile'
    post '/dang-ky' => 'users#create', :as => 'dang-ky'
    post '/orders/caculatingOrder' => 'orders#caculatingOrder', :as => 'caculatingOrder'
    post '/orders/updateOrderStatus' => 'orders#updateOrderStatus', :as => 'updateOrderStatus'
    post '/users/getListShipper' => 'users#getListShipper', :as => 'getListShipper'
    post '/users/refreshToken' => 'users#refreshToken', :as => 'refreshToken'
    
  end
  
  resources :home, :session
  
  get '/dang-xuat' => 'session#destroy', :as => 'dang-xuat'
  get '/dang-nhap' => 'session#new', :as => 'dang-nhap'
  

end

app/controllers/api/orders_controller.rb
class Api::OrdersController < Api::ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create, :updateOrderStatus, :import, :caculatingOrder]
  
  before_filter :verify_authorzation
  before_filter :verify_content_type, :only => [:create, :updateOrderStatus]
  before_filter :validate_order, :only => [:create]
  
  
  def index
    if !params[:order_code].nil?
      @orders = Order.where(order_code: params[:order_code], delete_flag: 0).order(id: :desc).first
      
      if @orders.created_by != @user.id.to_s && @user.id == 3
        return render json: {
         "status": "NOK",
         "code": "201",
         "messages":"Đơn hàng không tồn tại."
        }
      end
    elsif !params[:created_at].nil?
      if params[:skip].nil? || params[:take].nil?
        return render json: {
           "status": "NOK",
           "code": "201",
           "messages":"Truy vấn không hợp lệ, vui lòng kiểm tra lại."
          } 
      end
      @date = Date.parse(params[:created_at].to_s)
      @orders = Order.where(delete_flag: 0, created_by: @user.id.to_s).where(:created_at => @date.beginning_of_day..@date.end_of_day).order(id: :desc).offset(params[:skip]).limit(params[:take])
      #@orders = @orders.limit(params[:take]).offset(params[:skip])
    else
      if params[:skip].nil? || params[:take].nil?
        return render json: {
           "status": "NOK",
           "code": "201",
           "messages":"Truy vấn không hợp lệ, vui lòng kiểm tra lại."
          } 
      end
      if @user.role_id == 3
        @orders = Order.where(created_by: @user.id.to_s, delete_flag: 0).order(id: :desc).offset(params[:skip]).limit(params[:take])
      else
        @orders = Order.where(delete_flag: 0).order(id: :desc).offset(params[:skip]).limit(params[:take])
      end
      
      if !params[:orderStatus].nil?
        if params[:orderStatus] == "Nok"
          @orders = @orders.where.not(order_status_id: 7).where.not(order_status_id: 11).where.not(order_status_id: 12)
        else 
          @orders = @orders.where(order_status_id: 7).or(@orders.where(order_status_id: 11)).or(@orders.where(order_status_id: 12))
          
        end
      end
    end
    
    render json: {
           "status": "OK",
           "code": "200",
           "messages":"Danh sách Đơn Hàng",
           "result": @orders.as_json(except: [:receiver_id, :created_by, :sender_id, :delete_flag, :order_status_id, :package_id, :ship_type_id, :updated_by, :updated_at, :delete_flag], 
                include: {
                  ship_type: {
                    except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag]
                  },
                  package: {
                    except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag]
                  },
                  order_status: {
                    except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag]
                  },
                  receiver: {
                    except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag]
                  },
                  sender: {
                    except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag]
                  },
                  promotion: {
                    except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag, :discount_from, :discount_to, :count, :description, :discount]
                  }
               })
          }
  end

  def show
    
  end

  def create
    if Order.validUserForOrder?(@user.id)
      
      from = generateDistrictFromAddress(@data_parsed["sender_address"]+",Đà Nẵng,Việt Nam")
      to = generateDistrictFromAddress(@data_parsed["receiver_address"]+",Đà Nẵng,Việt Nam")
    
      fromlsData = from.split(/,/)
      tolsData = to.split(/,/)
      
      if fromlsData.length == 4
        fromAddress = fromlsData[0].nil? ? "" : fromlsData[0].to_s.strip
        fromWard = "";
        fromDistrict = fromlsData[1].nil? ? "" : fromlsData[1].to_s.strip.gsub('Q. ','')
        fromCity = fromlsData[2].nil? ? "" : fromlsData[2].to_s.strip
        fromCountry = fromlsData[3].nil? ? "" : fromlsData[3].to_s.strip
      else
        fromAddress = fromlsData[0].nil? ? "" : fromlsData[0].to_s.strip
        fromWard = fromlsData[1].nil? ? "" : fromlsData[1].to_s.strip
        fromDistrict = fromlsData[2].nil? ? "" : fromlsData[2].to_s.strip.gsub('Q. ','')
        fromCity = fromlsData[3].nil? ? "" : fromlsData[3].to_s.strip
        fromCountry = fromlsData[4].nil? ? "" : fromlsData[4].to_s.strip
      end
      
      if tolsData.length == 4
        toAddress = tolsData[0].nil? ? "" : tolsData[0].to_s.strip
        toWard = "";
        toDistrict = tolsData[1].nil? ? "" : tolsData[1].to_s.strip.gsub('Q. ','')
        toCity = tolsData[2].nil? ? "" : tolsData[2].to_s.strip
        toCountry = tolsData[3].nil? ? "" : tolsData[3].to_s.strip
      else
        toAddress = tolsData[0].nil? ? "" : tolsData[0].to_s.strip
        toWard = tolsData[1].nil? ? "" : tolsData[1].to_s.strip
        toDistrict = tolsData[2].nil? ? "" : tolsData[2].to_s.strip.gsub('Q. ','')
        toCity = tolsData[3].nil? ? "" : tolsData[3].to_s.strip
        toCountry = tolsData[4].nil? ? "" : tolsData[4].to_s.strip
      end
      
      @sender                           = Sender.new
      @sender.name                      = @data_parsed["sender_name"]
      @sender.phone                     = @data_parsed["sender_phone"]
      @sender.address                   = @data_parsed["sender_address"]
      @sender.district                  = fromDistrict
      @sender.city                      = fromCity
      @sender.created_by                = @user.name #it must be logged in user
      @sender.created_at                = DateTime.now
      @sender.updated_by                = @user.name #itmust be logged in user
      @sender.updated_at                = DateTime.now
      @sender.delete_flag               = 0
      
      @receiver                         = Receiver.new
      @receiver.name                    = @data_parsed["receiver_name"]
      @receiver.phone                   = @data_parsed["receiver_phone"]
      @receiver.address                 = @data_parsed["receiver_address"]
      @receiver.district                = toDistrict
      @receiver.city                    = toCity
      @receiver.created_by              = @user.name #it must be logged in user
      @receiver.created_at              = DateTime.now
      @receiver.updated_by              = @user.name #itmust be logged in user
      @receiver.updated_at              = DateTime.now
      @receiver.delete_flag             = 0
      
      @package              = Package.new
      @package.height       = @data_parsed["package_height"]
      @package.width        = @data_parsed["package_width"]
      @package.weight       = @data_parsed["package_weight"]
      @package.note         = @data_parsed["package_note"].nil? ? "" : @data_parsed["package_note"]
      @package.created_by   = @user.name #it must be logged in user
      @package.created_at   = DateTime.now
      @package.updated_by   = @user.name #itmust be logged in user
      @package.updated_at   = DateTime.now
      @package.delete_flag  = 0
      
      #save @receiver info
      if @receiver.save && @package.save && @sender.save
        
        ship_type_id = ShipType.find_by(name: @data_parsed["ship_type"]).id
        
        @order = Order.new
        @order.order_code       = Order.generateOrderCode
        @order.sender_id        = @sender.id #must be logged id
        @order.receiver_id      = @receiver.id
        @order.shipper_id       = 0 #it mean no shipper
        @order.package_id       = @package.id
        @order.ship_type_id     = ship_type_id
        @order.customer_code    = @data_parsed["customer_code"]
        @order.cod              = @data_parsed["cod"].to_i
        @order.order_status_id  = 1
        @order.promotion_id     = @promote.nil? ? 0 : @promote.id
        @order.created_by       = @user.id #it must be logged in user
        @order.created_at       = DateTime.now
        @order.updated_by       = @user.id #itmust be logged in user
        @order.updated_at       = DateTime.now
        @order.delete_flag      = 0
        
        if !@data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEFTWE-2017"
          @order.total = 20000
        elsif !@data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEFTEN-2017"
          @order.total = 10000
        elsif @data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEFTHI-2017"
          @order.total = 15000
        elsif @data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEF25K-2017"
          @order.total = 25000
        elsif @data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEF30K-2017"
          @order.total = 30000
        elsif @data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEF35K-2017"
          @order.total = 35000
        elsif @data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEF40K-2017"
          @order.total = 40000
        elsif @data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEF45K-2017"
          @order.total = 45000
        elsif @data_parsed["promotion_code"].nil? && @data_parsed["promotion_code"] == "CDVDEF50K-2017"
          @order.total = 50000
        else
          # from = @sender.address+","+@sender.district+","+@sender.city+",Việt Nam"
          # to = @receiver.address+","+@receiver.district+","+@receiver.city+",Việt Nam"
          distanceValue, distanceKm = generateDistanceBetween2points(from, to)
          baseRate = getBaseRate(ship_type_id.to_s)
          
          @order.total = caculated(baseRate, distanceValue, ship_type_id.to_s)
        end
        
        if @order.save

app/controllers/management/application_controller.rb
class Management::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper
  include Management::OrdersHelper
  
  helper_method :current_user, :is_admin?
  
  layout 'management/admin'
  
  
  # before_action :set_locale
  
  # def change_locale_path
  #     #if current_user
  #     #  current_user.locale = params[:locale]
  #     #  current_user.save
  #     #else
  #       I18n.locale = params[:locale]
  #     #end
      
  #     #redirect_to root_url  
  #     #redirect_to :back
  # end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def is_admin?
    self.current_user.role.name == "Admin"
  end
  
  def is_member?
    self.current_user.role.name == "Thành Viên"
  end
  
  def verify_logged
    if session[:user_id].nil?
      redirect_to new_session_path
    else
      params[:user_id] = session[:user_id]
    end
  end
  
  # private
  #   def set_locale
  #     I18n.locale = params[:locale] if params[:locale].present?
  #     # current_user.locale
  #     # request.subdomain
  #     # request.ENV["HTTP_ACCEPT_LANGUAGE"]
  #     # request.remote_ip
  #     # current_uri = request.env['PATH_INFO']
      
  #     # unless current_uri == "/"+params[:locale]+"/admin/dashboard" 
  #     #   redirect_to admin_dashboard_index_path
  #     # end
  #   end
  
  #   def default_url_options(options = {})
  #     {locale: I18n.locale}.merge options
  #   end
    
    
end

app/controllers/management/customer_types_controller.rb
class Management::CustomerTypesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @customerType = CustomerType.new
  end

  def create
    @customerType = CustomerType.new(customerType_params)
    @customerType.created_by = current_user.name
    @customerType.updated_by = current_user.name
    @customerType.delete_flag = 0
    
    if @customerType.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_customer_types_path
    else
      flash[:success] = 'Tạo mới thất bại, vui lòng kiểm tra lại'
      render 'new'
    end
  end

  def index
    @customerTypes = CustomerType.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def customerType_params
      params.require(:customer_type).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/dashboard_controller.rb
class Management::DashboardController < Management::ApplicationController
  before_filter :verify_logged
  
  def index
    #get tổng số đơn
    @totalOrder = Order.where(created_by: current_user.id.to_s, delete_flag: 0).size.to_s
    
    #get đơn hàng trong tuần
    #curDate = Date.new.week
    #byebug
  end
end

app/controllers/management/order_analyzes_controller.rb
class Management::OrderAnalyzesController < Management::ApplicationController
  def index
    unless params[:shipperId].nil?
      
      unless params[:fromDate].nil?
        @fromDate = params[:fromDate]
      end
      
      unless params[:toDate].nil?
        @toDate = params[:toDate]
      end
      
      fDate = @fromDate.to_date
      fDate = (fDate-1).to_s + " 17:00:00"
      
      tDate = @toDate.to_date
      tDate = tDate.to_s + " 16:59:59"
      
      @orders = Order.where("updated_at": fDate..tDate).order(id: :desc)
      
      if params[:orderStatusId] != "0"
        @orders = @orders.where('order_status_id': params[:orderStatusId].to_i)
      end
      
      if params[:shipperId] != "0"
        @orders = @orders.where('shipper_id': params[:shipperId].to_i)
      end
      
      if params[:senderId] != "0"
        cusName = User.find(params[:senderId]).profile.full_name
        @lsCustomerId = Sender.where(name: cusName, delete_flag: 0).select(:id)
        @orders = @orders.where(sender_id: @lsCustomerId)
      end
      
      @totalCod = @orders.sum("cod")
      @totalFee = @orders.sum("total")
      
    end
    
    #Order.where('updated_at': "2017-07-22 17:00:00".."2017-07-23 16:59:59")
    
    @users = User.includes(:profile).where(delete_flag: 0, role_id: 2)
    @customer = User.includes(:profile).where(delete_flag: 0, role_id: 3)
    @orderStatus = OrderStatus.where(delete_flag: 0)
  end
end

app/controllers/management/order_histories_controller.rb
class Management::OrderHistoriesController < Management::ApplicationController
  def index
    if params[:orderId].nil?
      @orders = nil
    else
      order = Order.find_by(order_code: params[:orderId])
      unless order.nil?
        @orders = OrderHistory.where(order_id: order.id)
      end
    end
    
  end
end

app/helpers/api/orders_helper.rb
module Api::OrdersHelper
end

app/helpers/management/customer_types_helper.rb
module Management::CustomerTypesHelper
end

app/helpers/management/dashboard_helper.rb
module Management::DashboardHelper
end

app/helpers/management/order_analyzes_helper.rb
module Management::OrderAnalyzesHelper
end

app/helpers/management/order_histories_helper.rb
module Management::OrderHistoriesHelper
end

app/helpers/management/order_statuses_helper.rb
module Management::OrderStatusesHelper
end

app/views/management/orders/create.html.erb
<h1>Admin::Orders#create</h1>
<p>Find me in app/views/admin/orders/create.html.erb</p>

app/views/management/orders/destroy.html.erb
<h1>Admin::Orders#destroy</h1>
<p>Find me in app/views/admin/orders/destroy.html.erb</p>

app/views/management/orders/importView.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Quản lý Đơn Hàng<small></small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <%= render 'partials/management/notification' %>
          <div class="x_content">
                    <p>Vui lòng kéo file dữ liệu vào khu vực này, để tiến hành tải thông tin đơn hàng lên hệ thống.</p>
                    <form id="uploadForm" action="import" class="dropzone"></form>
                    <br />
                    <br />
                    <br />
                    <br />
          </div>
        </div>
      </div>
    </div>
 </div>
</div>
<script>
     $("#uploadForm").bind('ajax:complete', function() {
         // tasks to do 
        alert("done");
     });
</script>

app/views/management/orders/index.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Quản lý Đơn Hàng <small></small></h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" id="txtSearchOrder" class="form-control" value='<%=@searchData %>' placeholder="Số ĐT, Địa Chỉ đơn hàng">
            <span class="input-group-btn">
              <!--<button class="btn btn-default" type="button">Go!</button>-->
              <button type="button" id="btnSearchOrder" class="btn btn-default">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">

      <div class="col-md-12 col-sm-12 col-xs-12">
        
        <div class="x_panel">
          <%= render 'partials/management/notification' %>
          
          
          <%= link_to "Thêm mới", new_management_order_path, class: "btn btn-success pull-right" %>
          <% unless is_member? %>
          <%= link_to "Thêm Cho Người Dùng", management_addForCustomerView_path, class: "btn btn-primary pull-right" %>
          <% end %>
          <%= link_to "Thêm Hàng Loạt", management_importView_path, class: "btn btn-info pull-right" %>
          <div class="x_content">
            <div class="table-responsive">
              <table class="table table-striped jambo_table bulk_action">
                <thead>
                  <tr class="headings">
                    <th>
                      <input type="checkbox" id="check-all" class="flat">
                    </th>
                    <th class="column-title">Mã CDV </th>
                    <th class="column-title">Mã Khách </th>
                    <th class="column-title">Từ</th>
                    <th class="column-title">Đến</th>
                    <th class="column-title">Trạng Thái</th>
                    <th class="column-title">Người Trả</th>
                    <th class="column-title">Đơn giá</th>
                    <th class="column-title">COD</th>
                    <th class="column-title no-link last"><span class="nobr">Actions</span>
                    </th>
                    
                  </tr>
                </thead>

                <tbody>
                  <% @orders.each do |f| %>
                    <tr class="even pointer">
                      <td class="a-center ">
                        <input type="checkbox" class="flat" name="table_records">
                      </td>
                      <td class=" "><%= link_to(f.order_code,management_order_path(f)) %></td>
                      <td class=" "><%= f.customer_code.nil? ? "" : f.customer_code.strip %></td>
                      <td class=" "><%= f.sender.nil? ? "Lỗi Không có tên người Gởi" : f.sender.name %></td>
                      <td class=" ">
                        <% if f.receiver.nil? %>
                          Lỗi, Không có tên người gởi
                        <% else %>
                          <%= f.receiver.address %>
                        <% end %>
                      </td>
                      <td class=" "><b><%= f.order_status.nil? ? "Lỗi, Không có trạng thái đơn hàng" : f.order_status.name %></b></td>
                      <td class=" "><%= f.payer == "Sender" ? "Người Gởi" : "Người Nhận" %></td>
                      <td class=" "><%= f.total.nil? ? "Lỗi, không có total" : comma_numbers(f.total) %> VND</td>
                      <td class=" "><%= f.cod.nil? ? "Lỗi, không có COD" : comma_numbers(f.cod.to_i) %> VND</td>
                      <td class=" ">
                        <% if f.order_status_id < 5 && isOwner?(f.created_by) %>
                          <%= link_to "Cập Nhật", edit_management_order_path(f), class:'btn btn-primary' %>
                        <% end %>
                        <% if f.order_status_id < 11 %>
                          <% unless is_member? %>
                            <button type="button" class="btn btn-success" onclick="openPopup(<%= f.id %>, <%= f.order_code %>)" id="btnConfirm" data-target=".bs-example-modal-sm">Duyệt Đơn</button>
                          <% end %>
                        <% end %>
                        <% if f.order_status_id < 3 && isOwner?(f.created_by) %>
                          <%= link_to "Xóa", management_order_path(f), class:'btn btn-danger', method: :delete, data: {confirm: "Bạn có muốn xóa Đơn hàng này ???"} %>
                        <% end %>
                      </td>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade bs-example-modal-sm" tabindex="-1" id="confirmModal" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel">Cân Đẩu Vân Express - Cập Nhật Trạng Thái</h4>
                </div>
                <input type="hidden" id="orderId">
                <div class="modal-body">
                  <h4>Đơn hàng: <label id="confirmOrderId"></label></h4>
                  <p><label class="control-label col-md-3 col-sm-3 col-xs-12">Trạng Thái</label></p>
                  <p><select id="cbxStatus" class="form-control">
                    <option>- Chọn Trạng Thái -</option>
                    <option value="1">Mới Tạo</option>
                    <option value="2">Xác Nhận</option>
                    <option value="3">Đang Lấy Hàng</option>
                    <option value="4">Đã Lấy Hàng</option>
                    <option value="5">Đang Giao Hàng</option>
                    <option value="6">Chờ Giao Lại</option>
                    <option value="7">Giao Hàng Thành Công</option>
                    <option value="8">Chờ Trả Hàng</option>
                    <option value="9">Đang Trả Hàng</option>
                    <option value="10">Chờ Thanh Toán</option>
                    <option value="11">Hoàn Tất</option>
                    <option value="12">Huỷ</option>
                  </select></p>
                  <p id="pShipperTitle" hidden="true"><label class="control-label col-md-3 col-sm-3 col-xs-12">Người Giao</label></p>
                  <p id="pShipperValue" hidden="true"><select id="cbxShipper" class="form-control">
                  </select></p>
                  <p><label class="control-label col-md-3 col-sm-3 col-xs-12">Nội Dung</label></p>
                  <textarea type="text" id="confirmOrderReason" name="confirmReason" class="form-control" rows="3"> </textarea>
                </div>
                <div class="modal-footer">
                  <button type="button" id="btnConfirmation" class="btn btn-success">Duyệt</button>
                  <button type="button" class="btn btn-info">Không Duyệt</button>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Tắt</button>
                </div>
              </div>
            </div>
          </div>
    </div>
  </div>
</div>

<script>
var listShipper = null;
var selectedId = 0;
var shipperId = 0;

// if (myParam != '') {
//   $('#txtSearchOrder').val(myParam);
// }

function openPopup(id, orderId) {
    //alert("Hello World "+id);
    getListShipper();
    $('#confirmModal').modal('show');
    $('#confirmOrderId').text(orderId);
    $('#orderId').attr("name", id);
}

function getListShipper() {
  $.ajax({
    type: "POST",
    url: "/management/users/getListShipper",
    success: function(returnValue){
          listShipper = returnValue.resultData.listShipper;
      },
      error: function(request,error) {
          alert('An error occurred attempting to get new e-number');
      }
  });
}

var e = $.Event( "keypress", { which: 13 } );

$("#txtSearchOrder").keyup(function(event){
    if(event.keyCode == 13){
        $("#btnSearchOrder").click();
    }
});


$('#btnSearchOrder').click(function(e) {
  console.log($('#txtSearchOrder').val());
  var searchData = $('#txtSearchOrder').val()
   
   
   var lastData = '<%= @searchData %>';
   
   if (lastData == '' && searchData == '') {
      alert('Vui lòng nhập Thông tin tìm kiếm');
   } else {
       if (searchData == '') {
         window.location.href = '/management/orders';
       } else {
         window.location.href = '/management/orders?searchData='+searchData;   
       }
      
   }
  
});

$('#cbxStatus').change(function(e) {
  selectedId = $('#cbxStatus')[0].selectedOptions[0].value;
  
  if(selectedId == 3 || selectedId == 5 || selectedId == 9) {//đang lấy hàng - đang giao hàng - đang trả hàng
    var cbxShipper = $('#cbxShipper');
    
    cbxShipper
      .find('option')
      .remove()
      .end()
      .append('<option>- Chọn Người Giao Hàng - </option>')
      .val('- Chọn Người Giao Hàng - ')
    ;
    
    for (var i = 0; i < listShipper.length; i++) {
      var option = document.createElement("option");
      option.value = listShipper[i].id;
      option.text = listShipper[i].profile.full_name;
      cbxShipper.append(option);
    }
  
    $('#pShipperTitle').removeAttr("hidden");
    $('#pShipperValue').removeAttr("hidden");
  } else {
    $('#pShipperTitle').attr("hidden","true");
    $('#pShipperValue').attr("hidden","true");
  }
  
});

$('#btnConfirmation').click(function(e) {
  var orderId = $('#orderId')[0].name;
  var content = $('#confirmOrderReason')[0].value;
  
  var currentUser = <%= current_user.id %>
  
  if(selectedId == 3 || selectedId == 5 || selectedId == 9) {//đang lấy hàng - đang giao hàng - đang trả hàng
    shipperId = $('#cbxShipper')[0].selectedOptions[0].value;
  }
  
   $.ajax({
      type: "POST",
      url: "/management/orders/updateOrderStatus",
      data: {orderId: orderId, statusId: selectedId, shipperId: shipperId, content: content, updatedBy: currentUser},
      success: function(returnValue){
            location.reload();
        },
        error: function(request,error) {
            alert('An error occurred attempting to get new e-number');
        }
    });
  
});

</script>

app/views/management/orders/update.html.erb
<h1>Admin::Orders#update</h1>
<p>Find me in app/views/admin/orders/update.html.erb</p>