config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'order_histories/index'
  end

  root 'home#index'
  
  namespace :api do
    resources :roles, :session, :ship_types, :profile, :users, :orders, :device_tokens, :order_histories
    
    get '/profile/getProfileByUserId/:user_id' => 'profile#getProfleByUserId', :as => 'getProfileByUId'
    get '/getUserProfile' => 'profile#getUserProfile', :as => 'getUserProfile'
    post '/orders/updateOrderStatus/:id' => 'orders#updateOrderStatus', :as => 'updateOrderStatus'
    post '/orders/updateShipper/:id' => 'orders#updateShipper', :as => 'updateShipper'
    post '/orders/import' => 'orders#import', :as => 'importOrder'
    post '/users/getUserByCB' => 'users#getByChatbot', :as => 'getByChatbot'
    post '/orders/caculatingOrder' => 'orders#caculatingOrder', :as => 'caculatingOrder'
    post '/users/getShipperByFullName' => 'users#getShipperByFullName', :as => 'getShipperByFullName'
    post '/users/getListShipper' => 'users#getListShipper', :as => 'getListShipper'
  end
  
  namespace :management do
    resources :dashboard, :roles, :users, :profiles, :order_statuses, :ship_types, :promotions, :orders, :customer_types, :order_histories, :order_analyzes
    get '/my-profile' => 'profiles#edit', :as => 'my-profile'
    get '/import_order' => 'orders#importView', :as => 'importView'
    get '/addForCustomerView' => 'orders#addForCustomerView', :as => 'addForCustomerView'
    post '/addForCustomer' => 'orders#addForCustomer', :as => 'addForCustomer'
    post '/import' => 'orders#import', :as => 'import'
    patch 'update-profile' => 'profiles#update', :as => 'update-profile'
    post '/dang-ky' => 'users#create', :as => 'dang-ky'
    post '/orders/caculatingOrder' => 'orders#caculatingOrder', :as => 'caculatingOrder'
    post '/orders/updateOrderStatus' => 'orders#updateOrderStatus', :as => 'updateOrderStatus'
    post '/users/getListShipper' => 'users#getListShipper', :as => 'getListShipper'
    post '/users/refreshToken' => 'users#refreshToken', :as => 'refreshToken'
    
  end
  
  resources :home, :session
  
  get '/dang-xuat' => 'session#destroy', :as => 'dang-xuat'
  get '/dang-nhap' => 'session#new', :as => 'dang-nhap'
  

end

app/models/profile.rb
class Profile < ApplicationRecord
    has_one :user
end

app/controllers/api/profile_controller.rb
class Api::ProfileController < Api::ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :update
  before_filter :verify_authorzation
  
  def show
    @profile = Profile.where(user_id: params[:user_id], delete_flag: 0)
    @user = User.find(params[:user_id])
    
    render json: {
     "status": "OK",
     "code": "200",
     "messages":"Lấy thông tin cá nhân thành công",
     "result": @user.as_json(except: [:encrypt_password, :salt, :delete_flag], 
          include: {
            profile: {
              except: [:delete_flag]
            }
         })
    }
  end
  
  def update
    information = request.raw_post
    data_parsed = JSON.parse(information)
  
    @user = User.find(params[:id])
    
    @profile = Profile.where(user_id: data_parsed["user_id"]).first
    @profile.full_name = data_parsed["full_name"]
    @profile.address = data_parsed["address"]
    @profile.district = data_parsed["district"]
    @profile.city = data_parsed["city"]
    @profile.updated_by = @user.name
    @profile.updated_at = DateTime.now
    
    @user.email = data_parsed["email"]
    @user.phone = data_parsed["phone"]
    @user.updated_by = @user.name
    @user.updated_at = DateTime.now
    
    if @profile.save && @user.save
      render json: {
       "status": "OK",
       "code": "200",
       "messages":"Cập nhật Thông tin cá nhân thành công",
       "result":  @user.as_json(except: [:encrypt_password, :salt, :delete_flag], 
          include: {
            profile: {
              except: [:delete_flag]
            }
         })
      }
    else
      render json: {
       "status": "NOK",
       "code": "401",
       "messages":"Cập nhật Thông tin cá nhân Lỗi, Vui lòng kiểm tra lại",
       "result": nil
      }
    end
    
  end

  def getByUserId
    
    @profile = Profile.where(user_id: params[:user_id], delete_flag: 0).first
    
    render json: {
     "status": "OK",
     "code": "200",
     "messages":"",
     "result": @profile
    }
  end
  
  def getUserProfile
    
    @user = User.find_by(token: @token)
    
    unless @user.nil?
        return render json: {
         "status": "OK",
         "code": "200",
         "messages":"Lấy thông tin cá nhân thành công",
         "result": @user.as_json(except: [:encrypt_password, :salt, :delete_flag], 
              include: {
                profile: {
                    except: [:delete_flag]
                },
                role: {
                    except: [:delete_flag]
                }
             })
        }
    else 
        return render json: {
         "status": "NOK",
         "code": "201",
         "messages":"Lấy thông tin cá nhân Thất bại",
         "result": ""
        }
    end
  end
end

app/controllers/management/application_controller.rb
class Management::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper
  include Management::OrdersHelper
  
  helper_method :current_user, :is_admin?
  
  layout 'management/admin'
  
  
  # before_action :set_locale
  
  # def change_locale_path
  #     #if current_user
  #     #  current_user.locale = params[:locale]
  #     #  current_user.save
  #     #else
  #       I18n.locale = params[:locale]
  #     #end
      
  #     #redirect_to root_url  
  #     #redirect_to :back
  # end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def is_admin?
    self.current_user.role.name == "Admin"
  end
  
  def is_member?
    self.current_user.role.name == "Thành Viên"
  end
  
  def verify_logged
    if session[:user_id].nil?
      redirect_to new_session_path
    else
      params[:user_id] = session[:user_id]
    end
  end
  
  # private
  #   def set_locale
  #     I18n.locale = params[:locale] if params[:locale].present?
  #     # current_user.locale
  #     # request.subdomain
  #     # request.ENV["HTTP_ACCEPT_LANGUAGE"]
  #     # request.remote_ip
  #     # current_uri = request.env['PATH_INFO']
      
  #     # unless current_uri == "/"+params[:locale]+"/admin/dashboard" 
  #     #   redirect_to admin_dashboard_index_path
  #     # end
  #   end
  
  #   def default_url_options(options = {})
  #     {locale: I18n.locale}.merge options
  #   end
    
    
end

app/controllers/management/customer_types_controller.rb
class Management::CustomerTypesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @customerType = CustomerType.new
  end

  def create
    @customerType = CustomerType.new(customerType_params)
    @customerType.created_by = current_user.name
    @customerType.updated_by = current_user.name
    @customerType.delete_flag = 0
    
    if @customerType.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_customer_types_path
    else
      flash[:success] = 'Tạo mới thất bại, vui lòng kiểm tra lại'
      render 'new'
    end
  end

  def index
    @customerTypes = CustomerType.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def customerType_params
      params.require(:customer_type).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/dashboard_controller.rb
class Management::DashboardController < Management::ApplicationController
  before_filter :verify_logged
  
  def index
    #get tổng số đơn
    @totalOrder = Order.where(created_by: current_user.id.to_s, delete_flag: 0).size.to_s
    
    #get đơn hàng trong tuần
    #curDate = Date.new.week
    #byebug
  end
end

app/controllers/management/order_analyzes_controller.rb
class Management::OrderAnalyzesController < Management::ApplicationController
  def index
    unless params[:shipperId].nil?
      
      unless params[:fromDate].nil?
        @fromDate = params[:fromDate]
      end
      
      unless params[:toDate].nil?
        @toDate = params[:toDate]
      end
      
      fDate = @fromDate.to_date
      fDate = (fDate-1).to_s + " 17:00:00"
      
      tDate = @toDate.to_date
      tDate = tDate.to_s + " 16:59:59"
      
      @orders = Order.where("updated_at": fDate..tDate).order(id: :desc)
      
      if params[:orderStatusId] != "0"
        @orders = @orders.where('order_status_id': params[:orderStatusId].to_i)
      end
      
      if params[:shipperId] != "0"
        @orders = @orders.where('shipper_id': params[:shipperId].to_i)
      end
      
      if params[:senderId] != "0"
        cusName = User.find(params[:senderId]).profile.full_name
        @lsCustomerId = Sender.where(name: cusName, delete_flag: 0).select(:id)
        @orders = @orders.where(sender_id: @lsCustomerId)
      end
      
      @totalCod = @orders.sum("cod")
      @totalFee = @orders.sum("total")
      
    end
    
    #Order.where('updated_at': "2017-07-22 17:00:00".."2017-07-23 16:59:59")
    
    @users = User.includes(:profile).where(delete_flag: 0, role_id: 2)
    @customer = User.includes(:profile).where(delete_flag: 0, role_id: 3)
    @orderStatus = OrderStatus.where(delete_flag: 0)
  end
end

app/controllers/management/order_histories_controller.rb
class Management::OrderHistoriesController < Management::ApplicationController
  def index
    if params[:orderId].nil?
      @orders = nil
    else
      order = Order.find_by(order_code: params[:orderId])
      unless order.nil?
        @orders = OrderHistory.where(order_id: order.id)
      end
    end
    
  end
end

app/controllers/management/order_statuses_controller.rb
class Management::OrderStatusesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @order_status = OrderStatus.new
  end

  def create
    @order_status = OrderStatus.new(order_status_params)
    @order_status.created_by = "Admin"
    @order_status.updated_by = "Admin"
    @order_status.delete_flag = 0
    
    if @order_status.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_order_statuses_path
    else
      render 'new'
    end
  end

  def index
    @order_statuses = OrderStatus.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def order_status_params
      params.require(:order_status).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/profiles_controller.rb
class Management::ProfilesController < Management::ApplicationController
  before_filter :verify_logged 
  
  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    
    @profile = Profile.find_by(user_id: current_user.id)
    @profile.full_name = params[:profile][:full_name]
    @profile.address = params[:profile][:address]
    @profile.district = params[:profile][:district]
    @profile.city = "Đà Nẵng"
    @profile.updated_at = DateTime.now
    @profile.updated_by = current_user.name
    
    @user = User.find_by(id: current_user.id)
    @user.email = params[:user][:email]
    @user.phone = params[:user][:phone]
    
    if @profile.save && @user.save
      flash[:success] = 'Cập nhật thông tin thành công'
      redirect_to management_my_profile_path
    else
      flash[:error] = 'Cập nhật Thất bại, vui lòng kiểm tra lại'
      redirect_to management_my_profile_path
    end
    
  end
  
end

app/controllers/management/promotions_controller.rb
class Management::PromotionsController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotion_params)
    @promotion.created_by = "Admin"
    @promotion.updated_by = "Admin"
    @promotion.delete_flag = 0
    
    if @promotion.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_promotions_path
    else
      render 'new'
    end
  end

  def index
    @promotions = Promotion.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def promotion_params
      params.require(:promotion).permit(:code, :discount, :discount_from, :discount_to, :count, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/roles_controller.rb
class Management::RolesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @role.created_by = "Admin"
    @role.updated_by = "Admin"
    @role.delete_flag = 0
    
    if @role.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_roles_path
    else
      render 'new'
    end
  end

  def index
    @roles = Role.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    
    
  
    def role_params
      params.require(:role).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/ship_types_controller.rb
class Management::ShipTypesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @ship_type = ShipType.new
  end

  def create
    @ship_type = ShipType.new(ship_type_params)
    @ship_type.created_by = "Admin"
    @ship_type.updated_by = "Admin"
    @ship_type.delete_flag = 0
    
    if @ship_type.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_ship_types_path
    else
      render 'new'
    end
  end

  def index
    @ship_types = ShipType.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def ship_type_params
      params.require(:ship_type).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/helpers/api/profile_helper.rb
module Api::ProfileHelper
end

app/helpers/management/customer_types_helper.rb
module Management::CustomerTypesHelper
end

app/helpers/management/dashboard_helper.rb
module Management::DashboardHelper
end

app/helpers/management/order_analyzes_helper.rb
module Management::OrderAnalyzesHelper
end

app/helpers/management/order_histories_helper.rb
module Management::OrderHistoriesHelper
end

app/helpers/management/order_statuses_helper.rb
module Management::OrderStatusesHelper
end

app/views/management/profiles/edit.html.erb
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Thông Tin Cá Nhân</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">Go!</button>
            </span>
          </div>
        </div>
      </div>
    </div>
    
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
        <%= render 'partials/management/notification' %>
          <div class="x_title">
            <h2>Thông Tin <small>Cá nhân</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <!--<li><a href="#">Settings 1</a>-->
                  <!--</li>-->
                  <!--<li><a href="#">Settings 2</a>-->
                  <!--</li>-->
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="col-md-2 col-sm-2 col-xs-12 profile_left">
              <div class="profile_img">
                <div id="crop-avatar">
                  <!-- Current avatar -->
                  <%= image_tag("img.jpg", :alt => "Avata", :title => "Change the Avatar", :class => "img-responsive avatar-view") %>
                </div>
              </div>
              <a class="btn btn-success"><i class="fa fa-edit m-right-xs"></i> Hình đại diện</a>
              <br />
            </div>
            <div class="col-md-10 col-sm-10 col-xs-12">

              <div class="profile_title">
                <div class="col-md-6">
                  <h2>Cập nhật thông tin</h2>
                </div>
                <div class="col-md-6">
                  <!--<div id="reportrange" class="pull-right" style="margin-top: 5px; background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #E6E9ED">
                    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                    <span>December 30, 2014 - January 28, 2015</span> <b class="caret"></b>
                  </div>-->
                </div>
              </div>
              <!-- start of user-activity-graph -->
                  <br/>
                <%= form_for [:management, @user],:url => management_update_profile_path, :html => {:class => 'form-horizontal form-label-left'} do |f| %>
                    <% if @user.customer_type_id == 3 || @user.role_id == 1 %>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Token</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :token, class:'form-control col-md-7 col-xs-12', required: 'require', disabled: 'disabled' %>
                        </div>
                    </div>
                    <% end %>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Địa chỉ Email</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :email, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="description">Số điện thoại</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <%= f.text_field :phone, class:'form-control col-md-7 col-xs-12', required: 'require' %>
                        </div>
                    </div>
                    <%= fields_for @user.profile do |profile_form| %>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Tên Đầy đủ</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <%= profile_form.text_field :full_name, class:'form-control col-md-7 col-xs-12', placeholder:'Vui lòng nhập Họ Tên đầy đủ', 'required' => 'required' %>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Địa chỉ</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <%= profile_form.text_field :address, class:'form-control col-md-7 col-xs-12', placeholder:'Số nhà, Tên Đường hoặc (Tổ, Thôn, Phường, Xã)', 'required' => 'required' %>
                            </div>
                        </div>
                        <div class="item form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Quận / Huyện</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <%= profile_form.text_field :district, class:'form-control col-md-7 col-xs-12', placeholder:'Tên Quận / Huyện tại TP Đà Nẵng', 'required' => 'required' %>
                            </div>
                        </div>
                    <% end %>
                    
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                          <%= f.submit "Cập Nhật", class:'btn btn-success' %>
                        </div>
                    </div>
                <% end %>
              <!-- end of user-activity-graph -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/management/profiles/update.html.erb
<h1>Management::Profiles#update</h1>
<p>Find me in app/views/management/profiles/update.html.erb</p>