config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    get 'order_histories/index'
  end

  root 'home#index'
  
  namespace :api do
    resources :roles, :session, :ship_types, :profile, :users, :orders, :device_tokens, :order_histories
    
    get '/profile/getProfileByUserId/:user_id' => 'profile#getProfleByUserId', :as => 'getProfileByUId'
    get '/getUserProfile' => 'profile#getUserProfile', :as => 'getUserProfile'
    post '/orders/updateOrderStatus/:id' => 'orders#updateOrderStatus', :as => 'updateOrderStatus'
    post '/orders/updateShipper/:id' => 'orders#updateShipper', :as => 'updateShipper'
    post '/orders/import' => 'orders#import', :as => 'importOrder'
    post '/users/getUserByCB' => 'users#getByChatbot', :as => 'getByChatbot'
    post '/orders/caculatingOrder' => 'orders#caculatingOrder', :as => 'caculatingOrder'
    post '/users/getShipperByFullName' => 'users#getShipperByFullName', :as => 'getShipperByFullName'
    post '/users/getListShipper' => 'users#getListShipper', :as => 'getListShipper'
  end
  
  namespace :management do
    resources :dashboard, :roles, :users, :profiles, :order_statuses, :ship_types, :promotions, :orders, :customer_types, :order_histories, :order_analyzes
    get '/my-profile' => 'profiles#edit', :as => 'my-profile'
    get '/import_order' => 'orders#importView', :as => 'importView'
    get '/addForCustomerView' => 'orders#addForCustomerView', :as => 'addForCustomerView'
    post '/addForCustomer' => 'orders#addForCustomer', :as => 'addForCustomer'
    post '/import' => 'orders#import', :as => 'import'
    patch 'update-profile' => 'profiles#update', :as => 'update-profile'
    post '/dang-ky' => 'users#create', :as => 'dang-ky'
    post '/orders/caculatingOrder' => 'orders#caculatingOrder', :as => 'caculatingOrder'
    post '/orders/updateOrderStatus' => 'orders#updateOrderStatus', :as => 'updateOrderStatus'
    post '/users/getListShipper' => 'users#getListShipper', :as => 'getListShipper'
    post '/users/refreshToken' => 'users#refreshToken', :as => 'refreshToken'
    
  end
  
  resources :home, :session
  
  get '/dang-xuat' => 'session#destroy', :as => 'dang-xuat'
  get '/dang-nhap' => 'session#new', :as => 'dang-nhap'
  

end

app/controllers/management/application_controller.rb
class Management::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper
  include Management::OrdersHelper
  
  helper_method :current_user, :is_admin?
  
  layout 'management/admin'
  
  
  # before_action :set_locale
  
  # def change_locale_path
  #     #if current_user
  #     #  current_user.locale = params[:locale]
  #     #  current_user.save
  #     #else
  #       I18n.locale = params[:locale]
  #     #end
      
  #     #redirect_to root_url  
  #     #redirect_to :back
  # end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def is_admin?
    self.current_user.role.name == "Admin"
  end
  
  def is_member?
    self.current_user.role.name == "Thành Viên"
  end
  
  def verify_logged
    if session[:user_id].nil?
      redirect_to new_session_path
    else
      params[:user_id] = session[:user_id]
    end
  end
  
  # private
  #   def set_locale
  #     I18n.locale = params[:locale] if params[:locale].present?
  #     # current_user.locale
  #     # request.subdomain
  #     # request.ENV["HTTP_ACCEPT_LANGUAGE"]
  #     # request.remote_ip
  #     # current_uri = request.env['PATH_INFO']
      
  #     # unless current_uri == "/"+params[:locale]+"/admin/dashboard" 
  #     #   redirect_to admin_dashboard_index_path
  #     # end
  #   end
  
  #   def default_url_options(options = {})
  #     {locale: I18n.locale}.merge options
  #   end
    
    
end

app/controllers/management/customer_types_controller.rb
class Management::CustomerTypesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @customerType = CustomerType.new
  end

  def create
    @customerType = CustomerType.new(customerType_params)
    @customerType.created_by = current_user.name
    @customerType.updated_by = current_user.name
    @customerType.delete_flag = 0
    
    if @customerType.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_customer_types_path
    else
      flash[:success] = 'Tạo mới thất bại, vui lòng kiểm tra lại'
      render 'new'
    end
  end

  def index
    @customerTypes = CustomerType.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def customerType_params
      params.require(:customer_type).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/dashboard_controller.rb
class Management::DashboardController < Management::ApplicationController
  before_filter :verify_logged
  
  def index
    #get tổng số đơn
    @totalOrder = Order.where(created_by: current_user.id.to_s, delete_flag: 0).size.to_s
    
    #get đơn hàng trong tuần
    #curDate = Date.new.week
    #byebug
  end
end

app/controllers/management/order_analyzes_controller.rb
class Management::OrderAnalyzesController < Management::ApplicationController
  def index
    unless params[:shipperId].nil?
      
      unless params[:fromDate].nil?
        @fromDate = params[:fromDate]
      end
      
      unless params[:toDate].nil?
        @toDate = params[:toDate]
      end
      
      fDate = @fromDate.to_date
      fDate = (fDate-1).to_s + " 17:00:00"
      
      tDate = @toDate.to_date
      tDate = tDate.to_s + " 16:59:59"
      
      @orders = Order.where("updated_at": fDate..tDate).order(id: :desc)
      
      if params[:orderStatusId] != "0"
        @orders = @orders.where('order_status_id': params[:orderStatusId].to_i)
      end
      
      if params[:shipperId] != "0"
        @orders = @orders.where('shipper_id': params[:shipperId].to_i)
      end
      
      if params[:senderId] != "0"
        cusName = User.find(params[:senderId]).profile.full_name
        @lsCustomerId = Sender.where(name: cusName, delete_flag: 0).select(:id)
        @orders = @orders.where(sender_id: @lsCustomerId)
      end
      
      @totalCod = @orders.sum("cod")
      @totalFee = @orders.sum("total")
      
    end
    
    #Order.where('updated_at': "2017-07-22 17:00:00".."2017-07-23 16:59:59")
    
    @users = User.includes(:profile).where(delete_flag: 0, role_id: 2)
    @customer = User.includes(:profile).where(delete_flag: 0, role_id: 3)
    @orderStatus = OrderStatus.where(delete_flag: 0)
  end
end

app/controllers/management/order_histories_controller.rb
class Management::OrderHistoriesController < Management::ApplicationController
  def index
    if params[:orderId].nil?
      @orders = nil
    else
      order = Order.find_by(order_code: params[:orderId])
      unless order.nil?
        @orders = OrderHistory.where(order_id: order.id)
      end
    end
    
  end
end

app/controllers/management/order_statuses_controller.rb
class Management::OrderStatusesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @order_status = OrderStatus.new
  end

  def create
    @order_status = OrderStatus.new(order_status_params)
    @order_status.created_by = "Admin"
    @order_status.updated_by = "Admin"
    @order_status.delete_flag = 0
    
    if @order_status.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_order_statuses_path
    else
      render 'new'
    end
  end

  def index
    @order_statuses = OrderStatus.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def order_status_params
      params.require(:order_status).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/profiles_controller.rb
class Management::ProfilesController < Management::ApplicationController
  before_filter :verify_logged 
  
  def edit
    @user = User.find_by(id: current_user.id)
  end

  def update
    
    @profile = Profile.find_by(user_id: current_user.id)
    @profile.full_name = params[:profile][:full_name]
    @profile.address = params[:profile][:address]
    @profile.district = params[:profile][:district]
    @profile.city = "Đà Nẵng"
    @profile.updated_at = DateTime.now
    @profile.updated_by = current_user.name
    
    @user = User.find_by(id: current_user.id)
    @user.email = params[:user][:email]
    @user.phone = params[:user][:phone]
    
    if @profile.save && @user.save
      flash[:success] = 'Cập nhật thông tin thành công'
      redirect_to management_my_profile_path
    else
      flash[:error] = 'Cập nhật Thất bại, vui lòng kiểm tra lại'
      redirect_to management_my_profile_path
    end
    
  end
  
end

app/controllers/management/promotions_controller.rb
class Management::PromotionsController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @promotion = Promotion.new
  end

  def create
    @promotion = Promotion.new(promotion_params)
    @promotion.created_by = "Admin"
    @promotion.updated_by = "Admin"
    @promotion.delete_flag = 0
    
    if @promotion.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_promotions_path
    else
      render 'new'
    end
  end

  def index
    @promotions = Promotion.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def promotion_params
      params.require(:promotion).permit(:code, :discount, :discount_from, :discount_to, :count, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/roles_controller.rb
class Management::RolesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    @role.created_by = "Admin"
    @role.updated_by = "Admin"
    @role.delete_flag = 0
    
    if @role.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_roles_path
    else
      render 'new'
    end
  end

  def index
    @roles = Role.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    
    
  
    def role_params
      params.require(:role).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/ship_types_controller.rb
class Management::ShipTypesController < Management::ApplicationController
  before_filter :verify_logged
  
  def new
    @ship_type = ShipType.new
  end

  def create
    @ship_type = ShipType.new(ship_type_params)
    @ship_type.created_by = "Admin"
    @ship_type.updated_by = "Admin"
    @ship_type.delete_flag = 0
    
    if @ship_type.save
      flash[:success] = 'Tạo mới thành công'
      redirect_to management_ship_types_path
    else
      render 'new'
    end
  end

  def index
    @ship_types = ShipType.where(delete_flag: 0).all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  private
    def ship_type_params
      params.require(:ship_type).permit(:name, :description, :created_by, :updated_by, :delete_flag)
    end
end

app/controllers/management/users_controller.rb
class Management::UsersController < Management::ApplicationController
  before_filter :verify_logged, :except => [:create, :getListShipper]
  
  def new
    @user = User.new
  end

  def create
    
    if params["email"].nil?
      @user = User.new(user_params)
      @user.created_by = current_user.name
      @user.updated_by = current_user.name
    else
      @user = User.new
      @user.email = params["email"]
      @user.phone = params["phone"]
      @user.password = params["password"]
      if @user.role_id.nil?
        @user.role_id = 3
      end
      @user.created_by = "system"
      @user.updated_by = "system"
    end
    
    #generate Token
    
    o = [('a'..'z'), ('A'..'Z'), (0..9)].map(&:to_a).flatten
    @user.token = (0...32).map { o[rand(o.length)] }.join
    
    @user.provider = "Website"
    @user.delete_flag = 0
    
    #TODO: 
    #kiem tra user da ton tai hay chua (name/email/sdt)
    if User.isUserValid?(@user.name, @user.phone)
      if @user.save
        #create profile for user
        @profile = Profile.new
        @profile.user_id = @user.id
        @profile.delete_flag = 0
        @profile.created_by = "system"
        @profile.updated_by = "system"
        
        if @profile.save
          flash[:success] = 'Tạo mới thành công'
          sign_in @user
          if params["email"].nil?
            redirect_to management_users_path
          else
            redirect_to management_my_profile_path
          end
        end
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.email = params["user"]["email"]
    @user.phone = params["user"]["phone"]
    @user.name =  params["user"]["name"]
    @user.role_id = params["user"]["role_id"]
    @user.customer_type_id = params["user"]["customer_type_id"]
    
    if @user.save
      flash[:success] = 'Cập nhật thành công'
      redirect_to management_users_path
    else
      flash[:success] = 'Cập nhật Thất bại'
      render 'edit'
    end
  end

  def index
    @users = User.where(delete_flag: 0).all
  end

  def show
  end

  def destroy
  end
  
  def getListShipper
    @users = User.includes(:profile).where(delete_flag: 0, role_id: 2)
    
    render json: {
      "resultData" => {
        "listShipper" => @users.as_json(except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag],
                include: {
                  profile: {
                    except: [:created_by, :updated_by, :created_at, :updated_at, :delete_flag]
                  }
                }
              )
      }
    }
    
  end
  
  def refreshToken
    userId = params["id"]
    user = User.find(userId)
    o = [('a'..'z'), ('A'..'Z'), (0..9)].map(&:to_a).flatten
    user.token = (0...32).map { o[rand(o.length)] }.join
    
    if user.save
      render json: {
        "resultData" => {
          "msg" =>  "ok",
          "token" => user.token
        }
      }
    end
    
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :role_id, :userstatus_id, :customer_type_id, :email, :phone, :password, :token)
    end
end

app/helpers/management/customer_types_helper.rb
module Management::CustomerTypesHelper
end

app/helpers/management/dashboard_helper.rb
module Management::DashboardHelper
end

app/helpers/management/order_analyzes_helper.rb
module Management::OrderAnalyzesHelper
end

app/helpers/management/order_histories_helper.rb
module Management::OrderHistoriesHelper
end

app/helpers/management/order_statuses_helper.rb
module Management::OrderStatusesHelper
end

app/helpers/management/orders_helper.rb
module Management::OrdersHelper
    def isOwner?(createdBy)
        if createdBy.to_s == current_user.id.to_s
            return true
        else
            return false
        end
    end
    
    def is_member?
        self.current_user.role.name == "Người Dùng"
    end
end

app/helpers/management/profiles_helper.rb
module Management::ProfilesHelper
end

app/helpers/management/promotions_helper.rb
module Management::PromotionsHelper
end

app/views/partials/management/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    A Product of <a href="https://candauvan.vn">Cân Đẩu Vân</a> © 2017
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

app/views/partials/management/_menu.html.erb
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="#" class="site_title"><i class="fa fa-moon-o"></i> <span>CDV</span></a>
    </div>
    
    <div class="clearfix"></div>
    
    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_pic">
        <%= image_tag("img.jpg", class: "img-circle profile_img", alt: "...") %>
      </div>
      <div class="profile_info">
        <span>Welcome,</span>
        <h2><%= current_user.nil? ? "" : current_user.phone %></h2>
      </div>
    </div>
    <!-- /menu profile quick info -->
    
    <br />
    
    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>Thông Tin</h3>
        <ul class="nav side-menu">
          <% if is_admin? %>
          <li><a><i class="fa fa-home"></i> Thông Tin Chung <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li>
                <%= link_to "Dashboard", management_dashboard_index_path %>
              </li>
            </ul>
          </li>
          <li><a><i class="fa fa-desktop"></i> Quản lý<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to "Quản lý Người Dùng", management_users_path %></li>
              <li><%= link_to "Quản lý Quyền", management_roles_path %></li>
              <li><%= link_to "Quản lý Kiểu Vận Chuyển", management_ship_types_path %></li>
              <li><%= link_to "Quản lý Trạng Thái Đơn Hàng", management_order_statuses_path %></li>
              <li><%= link_to "Quản lý Khuyến Mãi", management_promotions_path %></li>
              <li><%= link_to "Quản lý Kiểu Người Dùng", management_customer_types_path %></li>
            </ul>
          </li>
          <li><a><i class="fa fa-bar-chart-o"></i> Thống Kê - Báo Cáo <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li>
                <%= link_to "Lịch sử Đơn Hàng", management_order_histories_path %>
              </li>
              <li>
                <%= link_to "Thống Kê Đơn Hàng", management_order_analyzes_path %>
              </li>
            </ul>
          </li>
          
          <% end %>
          <li>
            <li><a><i class="fa fa-desktop"></i> Quản lý Chung<span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><%= link_to "Thông Tin Cá Nhân", management_my_profile_path %></li>
              <li><%= link_to "Quản lý Đơn Hàng", management_orders_path %></li>
            </ul>
          </li>
          
          
          <!--<li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="general_elements.html">General Elements</a></li>
              <li><a href="media_gallery.html">Media Gallery</a></li>
              <li><a href="typography.html">Typography</a></li>
              <li><a href="icons.html">Icons</a></li>
              <li><a href="glyphicons.html">Glyphicons</a></li>
              <li><a href="widgets.html">Widgets</a></li>
              <li><a href="invoice.html">Invoice</a></li>
              <li><a href="inbox.html">Inbox</a></li>
              <li><a href="calendar.html">Calendar</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="tables.html">Tables</a></li>
              <li><a href="tables_dynamic.html">Table Dynamic</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="chartjs.html">Chart JS</a></li>
              <li><a href="chartjs2.html">Chart JS2</a></li>
              <li><a href="morisjs.html">Moris JS</a></li>
              <li><a href="echarts.html">ECharts</a></li>
              <li><a href="other_charts.html">Other Charts</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
              <li><a href="fixed_footer.html">Fixed Footer</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <div class="menu_section">
        <h3>Live On</h3>
        <ul class="nav side-menu">
          <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="e_commerce.html">E-commerce</a></li>
              <li><a href="projects.html">Projects</a></li>
              <li><a href="project_detail.html">Project Detail</a></li>
              <li><a href="contacts.html">Contacts</a></li>
              <li><a href="profile.html">Profile</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="page_403.html">403 Error</a></li>
              <li><a href="page_404.html">404 Error</a></li>
              <li><a href="page_500.html">500 Error</a></li>
              <li><a href="plain_page.html">Plain Page</a></li>
              <li><a href="login.html">Login Page</a></li>
              <li><a href="pricing_tables.html">Pricing Tables</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="#level1_1">Level One</a>
                <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li class="sub_menu"><a href="level2.html">Level Two</a>
                    </li>
                    <li><a href="#level2_1">Level Two</a>
                    </li>
                    <li><a href="#level2_2">Level Two</a>
                    </li>
                  </ul>
                </li>
                <li><a href="#level1_2">Level One</a>
                </li>
            </ul>
          </li>                  
          <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>-->
        </ul>
      </div>
    
    </div>
    <!-- /sidebar menu -->
    
    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">
      <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
      </a>
      <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
      </a>
      <%= link_to "" do %>
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      <% end %>
    </div>
    <!-- /menu footer buttons -->
    </div>
</div>

app/views/partials/management/_notification.html.erb
<% if flash[:success] %>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
      <strong><%=h flash[:success] %></strong>
    </div>
<% elsif flash[:error] %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= flash[:error].html_safe  %>
    </div>
<% elsif flash[:userInfo] && controller.controller_name == "orders" %>
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
      </button>
      <%= flash[:userInfo].html_safe  %>
    </div>
<% end %>

app/views/partials/management/_topnavigation.html.erb
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <%= image_tag("img.jpg",alt:"") %>
            <%= current_user.nil? ? "" : current_user.phone %>
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="/management/my-profile"> Thông tin cá nhân</a></li>
            <!--<li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>-->
            <li>
              <%= link_to dang_xuat_path do %>
                Đăng Xuất<i class="fa fa-sign-out pull-right"></i>
              <% end %>
            </li>
          </ul>
        </li>
        <!--<li role="presentation" class="dropdown">
          <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-envelope-o"></i>
            <span class="badge bg-green">6</span>
          </a>
          <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
            <li>
              <a>
                <span class="image">
                  <%= image_tag("img.jpg", alt: "Profile Image") %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image">
                  <%= image_tag("img.jpg", alt: "Profile Image") %>
                </span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><%= image_tag("img.jpg", alt: "Profile Image") %></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <a>
                <span class="image"><%= image_tag("img.jpg", alt: "Profile Image") %></span>
                <span>
                  <span>John Smith</span>
                  <span class="time">3 mins ago</span>
                </span>
                <span class="message">
                  Film festivals used to be do-or-die moments for movie makers. They were where...
                </span>
              </a>
            </li>
            <li>
              <div class="text-center">
                <a>
                  <strong>See All Alerts</strong>
                  <i class="fa fa-angle-right"></i>
                </a>
              </div>
            </li>
          </ul>
        </li>-->
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->